apiVersion: v1
kind: Service
metadata:
  name: dwk-environments-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 34.14.21.38 # Replace with your desired static IP (match with GCP reserved IP)
  selector:
    app: dwk-environments
  ports:
    - port: 80
      targetPort: 80
